use crate::runner;
use anyhow::Result;
use kei_arch_map::schema::{self, Module, Plan};
use std::fmt::Write as _;
use std::path::Path;

const VERSION: &str = env!("CARGO_PKG_VERSION");

pub fn run(plan_path: &Path, out_path: &Path) -> Result<()> {
    let root = runner::repo_root(plan_path)?;
    runner::confine_out(out_path, &root)?;
    let plan = schema::load(plan_path)?;
    let body = render_plan(&plan);
    std::fs::write(out_path, body)?;
    println!("wrote {}", out_path.display());
    Ok(())
}

fn render_plan(plan: &Plan) -> String {
    let mut out = String::new();
    write_header(&mut out);
    for module in &plan.modules {
        write_module(&mut out, module, plan.meta.github_blob_base.as_deref());
    }
    write_footer(&mut out);
    out
}

fn write_header(out: &mut String) {
    out.push_str("# Architecture Map\n\n");
    out.push_str("> **Generated by `kei-arch-map render`. Do not edit manually.**\n");
    out.push_str("> Source of truth: [`PLAN.toml`](PLAN.toml)\n");
    out.push_str("> Run `kei-arch-map verify` to check claim status.\n\n");
}

fn write_module(out: &mut String, module: &Module, gh_base: Option<&str>) {
    let _ = writeln!(out, "## `{}`\n", module.id);
    let path_str = module.path.display().to_string();
    let _ = writeln!(out, "[`{}`](../{})", path_str, path_str);
    if let Some(base) = gh_base {
        let _ = writeln!(out, " | [GitHub blob]({}{})", base, path_str);
    }
    out.push('\n');
    if let Some(desc) = &module.description {
        let _ = writeln!(out, "{}\n", desc);
    }
    write_claims_table(out, module);
}

fn write_claims_table(out: &mut String, module: &Module) {
    if module.claims.is_empty() {
        out.push_str("_No claims declared._\n\n");
        return;
    }
    out.push_str("| Claim | Description | Evidence kind |\n");
    out.push_str("|---|---|---|\n");
    for claim in &module.claims {
        let kind = schema::evidence_kind(&claim.evidence);
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}` |",
            claim.id,
            md_escape(&claim.description),
            kind
        );
    }
    out.push('\n');
}

fn write_footer(out: &mut String) {
    out.push_str("---\n");
    let _ = writeln!(
        out,
        "_Generated by kei-arch-map v{}. **Edit `arch/PLAN.toml` to change.**_",
        VERSION
    );
}

/// Minimal markdown table-cell escape: pipes and newlines.
fn md_escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}
