version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
  - package-ecosystem: npm
    directory: /_ts_packages
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
  - package-ecosystem: cargo
    directory: /_primitives/_rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
