#!/bin/sh
# PreToolUse(Edit|Write) — block hand-editing generated agent .md files.
#
# Generated files start with: <!-- GENERATED by _assembler ...
# Edit the manifest at _manifests/<name>.toml instead.
#
# Override: set AGENT_MIGRATION=1 in env to allow hand edits (migration / emergency).
#
# Stdin: JSON with tool_input.file_path

# Silent fall-through if jq is absent; otherwise `set -eu` would abort and
# Claude Code would refuse Edit/Write system-wide.
command -v jq >/dev/null 2>&1 || exit 0

_KEI_LIB="$(dirname "$0")/_lib/gate.sh"
if [ -r "$_KEI_LIB" ]; then . "$_KEI_LIB"; kei_hook_gate "no-hand-edit-agents" || exit 0; fi

set -eu

[ "${AGENT_MIGRATION:-0}" = "1" ] && exit 0

FILE=$(jq -r '.tool_input.file_path // empty')
[ -n "$FILE" ] || exit 0

# Only care about files directly under ~/.claude/agents/*.md
# (not blocks/, manifests/, assembler/, template, generated preview)
#
# NOTE on staleness: we use the `<!-- GENERATED by _assembler -->` marker
# on line 1 as the SOLE SOURCE OF TRUTH for "is this file generated?".
# Legacy agent .md files that were produced before the assembler existed
# (and therefore lack the marker) will pass this hook silently. That is
# intentional — the marker is how the assembler self-declares ownership,
# and any file without it is assumed hand-authored. Re-run the assembler
# to adopt an older file into the managed set.
case "$FILE" in
    "$HOME/.claude/agents/_"*) exit 0 ;;
    "$HOME/.claude/agents/"*.md) ;;
    *) exit 0 ;;
esac

# Detect generated marker in the first 10 lines (sole truth — see NOTE above)
if [ -f "$FILE" ] && head -10 "$FILE" | grep -q 'GENERATED by _assembler'; then
    NAME=$(basename "$FILE" .md)
    echo "[no-hand-edit-agents] BLOCKED: $FILE is generated." >&2
    echo "" >&2
    echo "Edit the manifest instead:" >&2
    echo "  ~/.claude/agents/_manifests/$NAME.toml" >&2
    echo "" >&2
    echo "Or edit a shared block:" >&2
    echo "  ~/.claude/agents/_blocks/<block>.md" >&2
    echo "" >&2
    echo "Override (emergency only): export AGENT_MIGRATION=1" >&2
    exit 1
fi

exit 0
